# modules/networking.nix
# @decision NET-01: port 22 open on public interface with key-only auth + fail2ban protection.
#   Deliberate: Tailscale-preferred deploy, but public SSH enables bootstrap/recovery when
#   Tailscale is unavailable (e.g., first boot, Tailscale misconfiguration).
# @decision NET-02: default-deny nftables firewall, allowPing + allowDHCP for bringup
# @decision NET-03: Tailscale VPN connected to tailnet
# @decision NET-04: ports 22, 80, 443, 22000 on public interface; all other services internal
# @decision NET-06: Tailscale reverse path filtering set to loose
# @decision NET-08: Only ed25519 host key — matches injected key, avoids ephemeral RSA/ECDSA regeneration
{ config, lib, pkgs, ... }:
let
  # Ports that must NEVER appear in allowedTCPPorts (internal services).
  # Services bind to localhost or are Tailscale-only — never on the public interface.
  # @decision NET-07: Build-time assertion prevents accidental public exposure of internal services.
  # All known service ports listed here for comprehensive assertion coverage.
  # Private overlay services may also add ports in their own networking override.
  internalOnlyPorts = {
    "6052" = "esphome";
    "6167" = "matrix-conduit";
    "8082" = "homepage-dashboard";
    "8086" = "dm-guide";
    "8123" = "home-assistant";
    "8384" = "syncthing-gui (localhost)";
    "9091" = "anthropic-secret-proxy";
    "18789" = "openclaw-mark";
    "18790" = "openclaw-lou";
    "18791" = "openclaw-alexia";
    "18792" = "openclaw-ari";
    "18793" = "openclaw-jordan-claw";
    "18794" = "openclaw-tal-claw";
    "19898" = "spacebot";
    "29317" = "mautrix-telegram";
    "29318" = "mautrix-whatsapp";
    "29328" = "mautrix-signal";
  };
  exposed = lib.filter (p: builtins.hasAttr (toString p) internalOnlyPorts) config.networking.firewall.allowedTCPPorts;
  exposedNames = map (p: "${toString p} (${internalOnlyPorts.${toString p}})") exposed;
in {
  assertions = [
    {
      assertion = exposed == [];
      message = "SECURITY: Internal service ports leaked into allowedTCPPorts: ${lib.concatStringsSep ", " exposedNames}. These must remain Tailscale-only (trustedInterfaces).";
    }
  ];

  # --- nftables backend ---
  networking.nftables.enable = true;
  networking.nftables.tables.agent-metadata-block = {
    family = "ip";
    content = ''
      chain output {
        type filter hook output priority 0; policy accept;
        ip daddr 169.254.169.254 drop
      }
    '';
  };

  # --- Firewall: per-interface trust ---
  networking.firewall = {
    enable = true;
    allowPing = true;
    # @decision NET-10: ports 80/443 for nginx (ACME HTTP-01 challenge + TLS reverse proxy)
    # @decision NET-11: port 22000 for Syncthing BEP (encrypted, certificate-authenticated)
    allowedTCPPorts = [ 22 80 443 22000 ];
    allowedUDPPorts = [ config.services.tailscale.port ];
    trustedInterfaces = [ "tailscale0" ];
  };

  # --- SSH hardening ---
  # @decision NET-12: fail2ban enabled via srvos server profile (automatic, no explicit config needed);
  #   protects port 22 from brute-force with progressive banning.
  # @decision NET-13: SSH hardened beyond key-auth — X11 off, MaxAuthTries 3, 30s grace window,
  #   client keepalive 5min to detect stale connections.
  services.openssh = {
    enable = true;
    openFirewall = false;
    hostKeys = [
      { type = "ed25519"; path = "/etc/ssh/ssh_host_ed25519_key"; }
    ];
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "prohibit-password";  # key-only root access for deploy pipeline
      X11Forwarding = false;
      MaxAuthTries = 3;
      LoginGraceTime = 30;
      ClientAliveInterval = 300;
      ClientAliveCountMax = 3;
    };
    # @decision NET-14: Override AuthorizedKeysFile to also check ~/.ssh/authorized_keys.
    # NixOS default only checks /etc/ssh/authorized_keys.d/%u (generated by activation).
    # On impermanence hosts, if activation ordering fails, this is the only way in.
    # The extra-files mechanism injects keys to /persist/root/.ssh/authorized_keys.
    extraConfig = lib.mkAfter ''
      AuthorizedKeysFile .ssh/authorized_keys /etc/ssh/authorized_keys.d/%u
    '';
  };

  # --- Tailscale VPN ---
  services.tailscale = {
    enable = true;
    authKeyFile = config.sops.secrets."tailscale-authkey".path;
    useRoutingFeatures = "client";   # auto-sets checkReversePath = "loose"
    extraUpFlags = [
      "--accept-routes"
    ];
  };
}
