#!/usr/bin/env bash
# tsurf-init.sh — Bootstrap a tsurf private overlay with a real root SSH key.
# Generates the root key, can materialize modules/root-ssh.nix in a private overlay,
# and optionally derives a sops age identity from the host SSH key when run on-target.
set -euo pipefail

KEY_PATH="${HOME}/.ssh/tsurf-root"
OVERLAY_DIR=""
GENERATE_AGE=false

usage() {
  cat <<'USAGE'
Usage: tsurf-init [--key-path PATH] [--overlay-dir DIR] [--age]

  --key-path PATH      Root SSH key path (default: ~/.ssh/tsurf-root)
  --overlay-dir DIR    Write modules/root-ssh.nix into a private overlay
  --age                Derive a sops age key from the target host SSH host key
USAGE
}

write_root_module() {
  local overlay_dir="$1"
  local module_path="${overlay_dir}/modules/root-ssh.nix"

  mkdir -p "${overlay_dir}/modules"
  if [[ -f "${module_path}" ]]; then
    echo "[ok] Existing overlay root SSH module kept: ${module_path}"
    return 0
  fi

  cat > "${module_path}" <<EOF
# modules/root-ssh.nix
# Root SSH access for this private overlay.
# Generated by \`nix run .#tsurf-init -- --overlay-dir ${overlay_dir}\`.
{ ... }: {
  users.users.root.openssh.authorizedKeys.keys = [
    "${PUB_KEY}"
  ];
}
EOF
  echo "[ok] Wrote ${module_path}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --key-path) KEY_PATH="$2"; shift 2 ;;
    --overlay-dir) OVERLAY_DIR="$2"; shift 2 ;;
    --age) GENERATE_AGE=true; shift ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

echo "=== tsurf init ==="

if [[ -f "${KEY_PATH}" ]]; then
  echo "[ok] Root SSH key already exists: ${KEY_PATH}"
else
  echo "[..] Generating root ed25519 key pair: ${KEY_PATH}"
  mkdir -p "$(dirname "${KEY_PATH}")"
  ssh-keygen -t ed25519 -C "tsurf-root@$(hostname -s 2>/dev/null || echo local)" -f "${KEY_PATH}" -N ""
  echo "[ok] Key generated."
fi

PUB_KEY="$(cat "${KEY_PATH}.pub")"
echo ""
echo "Root SSH public key:"
echo "  ${PUB_KEY}"
echo ""

if [[ -n "${OVERLAY_DIR}" ]]; then
  write_root_module "${OVERLAY_DIR}"
fi

if [[ "${GENERATE_AGE}" == "true" ]]; then
  SSH_HOST_KEY="/etc/ssh/ssh_host_ed25519_key"
  if [[ ! -f "${SSH_HOST_KEY}" ]]; then
    SSH_HOST_KEY="/persist/etc/ssh/ssh_host_ed25519_key"
  fi
  if [[ -f "${SSH_HOST_KEY}" ]]; then
    if command -v ssh-to-age >/dev/null 2>&1; then
      AGE_KEY="$(ssh-to-age -private-key -i "${SSH_HOST_KEY}" 2>/dev/null || true)"
      if [[ -n "${AGE_KEY}" ]]; then
        AGE_DIR="${HOME}/.config/sops/age"
        mkdir -p "${AGE_DIR}"
        echo "${AGE_KEY}" > "${AGE_DIR}/keys.txt"
        chmod 600 "${AGE_DIR}/keys.txt"
        echo "[ok] Age key derived and written to ${AGE_DIR}/keys.txt"
      else
        echo "[!!] ssh-to-age failed to derive key from ${SSH_HOST_KEY}"
      fi
    else
      echo "[!!] ssh-to-age not found — install it or use: nix shell nixpkgs#ssh-to-age"
    fi
  else
    echo "[!!] No SSH host key found at /etc/ssh/ or /persist/etc/ssh/"
    echo "     Run this on the target host after bootstrap, or provide the age key manually."
  fi
fi

ERRORS=0

if [[ ! -f "${KEY_PATH}" ]]; then
  echo "[FAIL] Root SSH private key not found: ${KEY_PATH}"
  ERRORS=$((ERRORS + 1))
fi

if [[ ! -f "${KEY_PATH}.pub" ]]; then
  echo "[FAIL] Root SSH public key not found: ${KEY_PATH}.pub"
  ERRORS=$((ERRORS + 1))
fi

if [[ -n "${OVERLAY_DIR}" && ! -f "${OVERLAY_DIR}/modules/root-ssh.nix" ]]; then
  echo "[FAIL] Missing generated overlay module: ${OVERLAY_DIR}/modules/root-ssh.nix"
  ERRORS=$((ERRORS + 1))
fi

if [[ "${ERRORS}" -eq 0 ]]; then
  echo ""
  echo "[ok] Setup validated. Next steps:"
  if [[ -n "${OVERLAY_DIR}" ]]; then
    echo "  1. Ensure ${OVERLAY_DIR}/modules/root-ssh.nix is imported by your private overlay"
    echo "  2. Store ${KEY_PATH} in a password manager and an offline backup"
    echo "  3. Keep the private key out of every repo and off every target host"
  else
    echo "  1. Set users.users.root.openssh.authorizedKeys.keys in your private overlay"
    echo "  2. Store ${KEY_PATH} in a password manager and an offline backup"
    echo "  3. Keep the private key out of every repo and off every target host"
  fi
else
  echo ""
  echo "[FAIL] ${ERRORS} validation error(s). Fix before proceeding."
  exit 1
fi
